[package]
name = "aspl"
description = "A Simple Programming Language."
license = "MIT"
repository = "https://github.com/qxb3/aspl"
version = "0.2.3"
edition = "2021"

[dependencies]
inline_colorization = "0.1.6"
