[package]
name = "aspl"
description = "A Really Shitty Programming Language"
license = "Unlicense"
repository = "https://github.com/qxb3/aspl"
version = "0.2.1"
edition = "2021"

[dependencies]
inline_colorization = "0.1.6"
